### ISSUE TITLE
The Variable Import Syntax in the _arrow.scss is wrong.

### ISSUE THREAD

**Issue by pratirupm** [kapoko/delicious-hamburgers#2]
![Annotation 2020-04-25 005241](https://user-images.githubusercontent.com/45709214/80249350-4a1bc280-868f-11ea-8d5c-3cc3f7132c5a.png)

**Comment by kapoko** [comment]
Thanks for noticing and posting the issue! Fixed in #[e8e83ed](https://github.com/kapoko/delicious-hamburgers/commit/e8e83ed278f60564bf533120686283117d526ffb), just released patch v1.0.1 including this commit.

Edit: closing issue! Please re-open if necessary.
