### ISSUE TITLE
Change color of hamburger dependent on dark/light mode

### ISSUE THREAD

**Issue by ghost** [kapoko/delicious-hamburgers#8]
Hey guys, big fan of the delicious-hamburgers project. I'm using it in my app and am trying to make the hamburger black when in light mode and white when in dark mode. I'm using React, Tailwind and NextJS. I can't seem to find a way to make it change colors depending on the theme.

Any help would be much appreciated, if it's not currently possible I understand. Thank you!

**Comment by kapoko** [comment]
Happy you like it. This should be easy enough to do, no matter which framework you use. The sass variables are there to make customizing easier but you can use normal css overrides to change the behavior based on what you want.

If you're using Tailwind you might not have sass enabled as it is not necessary for Tailwind, but for using this in NextJS you'd have to [enable sass in NextJS](https://nextjs.org/docs/basic-features/built-in-css-support#sass-support). 

If for example you have just the bars without a border or background (like on the demo page) you would use something like:

```scss
$hamburger-color: #000; /* This is the default anyway */

@import "~delicious-hamburgers/scss/base";
@import "~delicious-hamburgers/scss/animations/criss-cross";
```

Then later on create some css overrides. If it's just the bars you want to change color this should be enough:
```scss
@media (prefers-color-scheme: dark) { /* Or a custom .dark class attached to the body for example */
  .hamburger span.bar { 
    background-color: #fff;
  }
}
```
If there's also borders or backgrounds you want to change you need some more overrides. To checkout what classes you'd have to override you'd have to do some digging in [_base.scss](https://github.com/kapoko/delicious-hamburgers/blob/main/scss/_base.scss). 

Does this help?

**Comment by ghost** [comment]
```
@media (prefers-color-scheme: dark) { /* Or a custom .dark class attached to the body for example */
  .hamburger span.bar { 
    background-color: #fff;
  }
}
```

What do you mean here by "a custom .dark class attached to the body?" Or how would you implement that, cause that might be my solution.

The problem I'm having is that we have elected to use tailwind toggle of dark/light theme. So instead of being able to detect what user prefers, we want to just detect what the current theme is either using next themes or tailwind's built in light/dark class identifier and decide what to render. I like the idea of just doing that in an scss file but it doesn't work because prefers-color-scheme isn't what we want to use to decide this, we want to just see what theme is set.

Sorry I know this is probably more work than what it's worth. I get it if my question makes no sense.

Also huge thank you for responding so quickly, it is much appreciated!

**Comment by kapoko** [comment]
[Tailwind suggests adding a dark class to the `html` tag in javascript](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually) if you want users to be able to switch themselves. The implementation of a dark mode is up to you, but they give an example. [Here](https://stackoverflow.com/a/55537134)'s an example of how to do something like that in React / NextJS.

After that your scss could look something like: 

```scss
.dark {
  .hamburger span.bar { 
    background-color: #fff;
  }
}
```

**Comment by ghost** [comment]
woooow thank you so much. I think I owe you some lunch for helping my dumbass figure that one out. If you have one of those buymeacoffee links or something, hit me up. I feel immensely dense right now.
